name: Daily Palworld Backup

on:
  schedule:
    # 9AM Singapore (1AM UTC)
    - cron: '0 16 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python backup.py
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}

          REMOTE_FOLDER: ${{ secrets.REMOTE_FOLDER }}

          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

          GH_TOKEN: ${{ github.token }}

          GITHUB_REPOSITORY: ${{ github.repository }}
